"""add_generated_content_status

Revision ID: a05997b067b4
Revises: 3400c0c420c8
Create Date: 2026-05-03 23:29:09.188075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a05997b067b4'
down_revision: Union[str, Sequence[str], None] = '3400c0c420c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 기존 row 가 있는 환경에서도 NOT NULL 추가 가능하도록 server_default 명시.
    with op.batch_alter_table('generated_contents', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('status', sa.String(length=20),
                      nullable=False, server_default='published')
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generated_contents', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
